# FILE: main.py
filename = "lut_func.v"
scale = 2**32
max_32bit = 0xFFFFFFFF

# Thêm encoding='utf-8' cho chắc, nhưng nội dung mình sẽ để tiếng Anh/Việt không dấu
with open(filename, 'w', encoding='utf-8') as f:
    f.write("// File generated by Python - LUT Case for Division\n") # Tiếng Anh cho an toàn
    f.write("function [31:0] get_inverse;\n")
    f.write("    input [8:0] idx;\n")
    f.write("    begin\n")
    f.write("        case (idx)\n")
    
    for i in range(512):
        denom_approx = (i << 7) + 64
        
        if denom_approx == 0:
            val = max_32bit
        else:
            val = int(scale / denom_approx)
            if val > max_32bit: val = max_32bit
            
        f.write(f"            9'd{i}: get_inverse = 32'h{val:08x};\n")
    
    f.write("            default: get_inverse = 32'h00000000;\n")
    f.write("        endcase\n")
    f.write("    end\n")
    f.write("endfunction\n")

print(f"Done! Created {filename} successfully.")